version: "3.8"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - git-repos:/git-repos
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  git-repos:
    driver: local
